### ISSUE TITLE
Got an error when trying to run demo_3d_bunnies.py

### ISSUE THREAD

**Issue by yjhp1016** [taichi-dev/taichi_elements#101]
Hi I got an error when trying to run a demo demo_3d_bunnies.py, is it caused by using wrong version?  Thanks

[Taichi] version 1.0.3, llvm 10.0.0, commit fae94a21, win, python 3.9.12
C:\ProgramData\Anaconda3\lib\site-packages\taichi\__init__.py:69: DeprecationWarning: ti.ext_arr is deprecated. Please use ti.types.ndarray instead.
  warnings.warn(
Namespace(show=False, frames=300, res=256, out_dir=None)
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "d:\s01jy0\work\taichi_elements\demo\demo_3d_bunnies.py", line 67, in <module>
    mpm = MPMSolver(res=(R, R, R),
  File "d:\s01jy0\work\taichi_elements\engine\mpm_solver.py", line 107, in __init__
    ci21 = ti.type_factory.custom_int(21, True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\__init__.py", line 80, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'type_factory'

**Comment by yuanming-hu** [comment]
Just now merged https://github.com/taichi-dev/taichi_elements/pull/100, could you try again? @yjhp1016 Many thanks! :-)
