### ISSUE TITLE
Can experimentalist validate taichi_element by comparing your data to the literature in fluid mechanics? 

### ISSUE THREAD

**Issue by randomwangran** [taichi-dev/taichi_elements#11]
Dear all:

Really cool idea and really cool demos.

I am just curious to know that can experimentalist compare our
data to the video generated in this repo?

An example would be like this: in the '`demo_3d.py`' example, if we
remove the red/white rectangles, and just placing the green fluid
material in the whole computer would, we can simulate a case
called `Lid-driven cavity flow`, which is a benchmark test for the
computational fluid dynamics.

![image](https://user-images.githubusercontent.com/8197831/75837154-0218a780-5d92-11ea-9885-0987f181f45b.png)

[Above figure is taken from one the most widely used open source
codes in computational fluid dynamics researchers.](https://cfd.direct/openfoam/user-guide/v7-cavity/#x5-40002.1)

There's a lot of data for this benchmark case both from numerial
and experimental points of view.

If you need any help, I would like to help.

Regardless of the vaildation result, this programming language is
awsome.

Thanks for your contribution.

Sincerely,

Ran

**Comment by PavelBlend** [comment]
I did not program fluid physics, but I think this fluid simulator is not suitable for such purposes. This simulator is not intended for computational fluid dynamics. This simulator is provided to artists and is far from physical correctness (if I'm not mistaken). The goal of the simulator is to produce a visually pleasing picture, rather than perform calculations.

**Comment by randomwangran** [comment]
Thanks for clarification. I was so narrowed in my little research area: computational fluid dynamics (CFD). The first time I saw the video the project made, I was so interested in it. Anyway, I like to study this fantastic project. Maybe I will have some findings.
