### ISSUE TITLE
Create examples of blend scenes

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#25]
@yuanming-hu If I create simulation examples (*.blend files), then where are they best placed? Create a separate repository? *.blend files can be large.

**Comment by yuanming-hu** [comment]
As mentioned before I think we can (ab)use [Releases](https://github.com/taichi-dev/taichi_elements/releases) - the *.blend files are not really *releases*, but there's no better place to place these huge binary files...

**Comment by PavelBlend** [comment]
I thought, and it seems to me that maybe the release page does not take up examples of scenes? Better to leave the release page for blender addon. And I do not want to take a place for examples.
I want to create a separate repository in which to create examples. Each release in this repository will contain only one scene. Each scene will be a zip archive that contains a blend scene and the simulation result in the form of rendered mp4 video.

Here is an example video:
https://gfycat.com/ru/weeklyunripegoldeneye

**Comment by yuanming-hu** [comment]
That sounds good as well. If you would like to, feel free to use https://github.com/taichi-dev/taichi_elements_blender_examples. You are the admin of that repo.
