### ISSUE TITLE
Coordinate system

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#31]
I added examples of * .npy files for the demo_3d_mesh.py script. And I noticed that the coordinate system of the blender is different from the coordinate system of the demo examples. Suzanne is face up. Maybe unify the coordinate system and make it similar to Blender? In the blender, the following coordinate system:
+X - right
+Y - front
+Z - up

https://github.com/taichi-dev/taichi_elements_blender_examples#npy-examples

**Comment by yuanming-hu** [comment]
Actually, I would keep the coordinate system in the demos, since most 3D graphics researchers use a different convention:
+X: right
+Y: up
+Z: front

**Comment by PavelBlend** [comment]
Good. I am closing this issue.
