### ISSUE TITLE
Seeding error if the mesh is outside the domain

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#32]
An error is reproduced on this scene:
[seeding_bug.zip](https://github.com/taichi-dev/taichi_elements/files/4476918/seeding_bug.zip)

And at this commit:
b49cd08433afebd9816cb0b477aa70245a828464

Particles are created where there is no mesh:
![01](https://user-images.githubusercontent.com/7983249/79258600-0e654980-7e94-11ea-84f0-c02c35da090c.jpg)

And it seems to me that the borders / walls of the domain are too thick.

UPDATE: I think I realized the wall thickness has two voxels. But why exactly two and not one voxel?

**Comment by yuanming-hu** [comment]
I'll take a look at this now. 


> And it seems to me that the borders / walls of the domain are too thick.
> 
> UPDATE: I think I realized the wall thickness has two voxels. But why exactly two and not one voxel?

This is because MPM is a hybrid particle-grid simulation, and for the grid part we need some padding so that the particles do not move out of the domain. I guess we have to accept this drawback for now, and after we have #3, the grid will become infinitely large and we can git rid of these issues.

**Comment by PavelBlend** [comment]
The error with Suzanne disappeared. But I noticed strange behavior:
the walls of the domain are not the same thickness:
![01](https://user-images.githubusercontent.com/7983249/79364748-70848400-7f52-11ea-8c93-22636c45f18d.jpg)
![02](https://user-images.githubusercontent.com/7983249/79364764-74180b00-7f52-11ea-9ce5-737e19c23539.jpg)
![03](https://user-images.githubusercontent.com/7983249/79364769-767a6500-7f52-11ea-9422-9a922f353702.jpg)
[test_seed_all_domain.zip](https://github.com/taichi-dev/taichi_elements/files/4482598/test_seed_all_domain.zip)

I filled the whole domain with particles using cube emitter.

**Comment by yuanming-hu** [comment]
Ah sorry.. my bad. I just now update the PR #39, could you take a look?

About the wall thickness: I know it's too thick when we use grid size 32. For high-quality simulations, people can go up to 320x320x320 gird size, and then 3 cells are not too thich.

**Comment by PavelBlend** [comment]
resolved b836037114dbe2789554fac0368c74df731862b0
