### ISSUE TITLE
Travis CI tests

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#34]
It would be nice to have tests (for example, on travis ci) to be sure that each commit works.
@yuanming-hu Do you have experience with travis-ci? I have never integrated travis-ci, but I wrote tests.

**Comment by saullocastro** [comment]
@PavelBlend Google actions is much better now than Travis CI, you can check the following workflow for an updated example

https://github.com/saullocastro/bfsplate2d/blob/master/.github/workflows/pytest.yml

**Comment by yuanming-hu** [comment]
Hi @saullocastro thanks for the input! Could you provide more detail on why Github actions are better than Travis/AppVeyor? I'm not very familiar with GitHub actions, but I find Travis to do a decent job.

**Comment by PavelBlend** [comment]
@yuanming-hu I am trying to write tests on travis-ci, but I cannot install taichi on linux. Writes an error:
https://travis-ci.com/github/taichi-dev/taichi_elements/jobs/320494879#L176
```
Share object taichi_core import failed. If you are on Windows, please consider installing "Microsoft Visual C++ Redistributable" (https://aka.ms/vs/16/release/vc_redist.x64.exe)
```

How to fix it?

**Comment by yuanming-hu** [comment]
Quick solution: use `bionic` (Ubuntu 18.04)

https://github.com/yuanming-hu/taichi-wheels-test/blob/master/.travis.yml#L14

**Comment by PavelBlend** [comment]
I managed to install taichi, about when an test case starts, an error occurs:
https://travis-ci.com/github/taichi-dev/taichi_elements/jobs/320505928

What is the reason and how to fix it?

**Comment by yuanming-hu** [comment]
It seems that we are trying to create a window on Travis (which doesn't even have a GUI system, hence the crash) - can we avoid creating a `ti.GUI`?

https://travis-ci.com/github/taichi-dev/taichi_elements/jobs/320505928#L231

**Comment by saullocastro** [comment]
> Hi @saullocastro thanks for the input! Could you provide more detail on why Github actions are better than Travis/AppVeyor? I'm not very familiar with GitHub actions, but I find Travis to do a decent job.

@yuanming-hu  it is fully integrated with Github, performs faster and allows to do a cross-platform test matrix for Windows and Linux. I'm not sure of Travis CI now works with Windows.

**Comment by PavelBlend** [comment]
Hello @yuanming-hu 
I tried a lot to do tests for blender addon. But all to no avail.
I get this error:
https://travis-ci.com/github/taichi-dev/taichi_elements/builds/161256229#L328

I think even if you manage to fix this error, there will still be many difficulties in testing. In general, you will need to create nodes using python, and this is a time-consuming process. Writing tests can be time consuming and not the fact that this will produce a result. I suggest abandoning tests altogether. Moreover, the blender does not have tools for testing. Do you think it is worth abandoning the tests or not?

**Comment by yuanming-hu** [comment]
I agree that we should abandon Blender testing. Actually, I have no idea how to test a GUI system. Mocking might be a solution but clearly that's too much work.

Also, I believe since we are still changing interface actively, testing should better be postponed.

(And I'm not even sure if Blender will run under Travis without GUI :-(

**Comment by PavelBlend** [comment]
I will then remove all the tests that are now.

**Comment by yuanming-hu** [comment]
I think we can keep the demo tests since they are still useful. Blender tests needs more discussions in the future.
