### ISSUE TITLE
Optimize solver performance

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi_elements#4]

**Comment by yuanming-hu** [comment]
baseline
```
fill_dense:
 * range           x86_64    49.450 ms       gpu       18.888 ms
 * range_blocked   x86_64     4.238 ms       gpu        6.564 ms
 * struct          x86_64    11.295 ms       gpu        1.196 ms
mpm2d:
 * range           x86_64     0.790 ms       gpu        0.044 ms
 * struct          x86_64     0.786 ms       gpu        1.563 ms
```

**Comment by yuanming-hu** [comment]
Taichi@ef64ced8
optimized listgen
```
fill_dense:
 * flat_range                x86_64    21.658 ms       gpu        2.179 ms
 * flat_struct               x86_64    76.132 ms       gpu        1.171 ms
 * nested_range              x86_64    46.405 ms       gpu       17.833 ms
 * nested_range_blocked      x86_64     4.273 ms       gpu        6.665 ms
 * nested_struct             x86_64    11.001 ms       gpu        1.201 ms
mpm2d:
 * range                     x86_64     0.788 ms       gpu        0.045 ms
 * struct                    x86_64     0.789 ms       gpu        0.203 ms
```

**Comment by PavelBlend** [comment]
I have a question:
What stages of the simulation work on the video card?
Or can all the calculations be done only on the video card?

And can this issue be closed?

**Comment by yuanming-hu** [comment]
All simulation computations are on the video card, if you have one with CUDA 10 supported. Yes, this can be closed since the benchmarks here are no longer relevant. (Although I clearly need more time to finalized the optimizations... For the initial release I think the current performance should be fine.)

**Comment by PavelBlend** [comment]
That sounds cool. I have never met a simulator for a blender that could do a miscalculation on a video card. I think this will be the "business card" of taichi_elements.

**Comment by yuanming-hu** [comment]
Right, this is exactly the benefit of building everything on Taichi: it allows you to write a piece of code that runs on both CPU and GPU, without much installation trouble.
