### ISSUE TITLE
Not full particle seeding

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#43]
The mesh is not completely filled with particles. Here is a screenshot:
![01](https://user-images.githubusercontent.com/7983249/79635827-f8010b80-817b-11ea-86c2-d9fa2fafbf59.jpg)

This error is reproduced in this scene:
[test_05.zip](https://github.com/taichi-dev/taichi_elements/files/4496509/test_05.zip)

And at this commit:
d1848fdecd1318e16e31dcf6ba70921bec1f574f

**Comment by yuanming-hu** [comment]
Trying to reproduce this on my end, but I get undefined nodes in Blender:

![Screenshot from 2020-04-20 22-17-14](https://user-images.githubusercontent.com/6553256/79817993-b6778880-8354-11ea-97e4-5ef52c7a1345.png)

A quick question: is the mesh completely within the bounding cube? Currently the rasterizer will only seed within the simulation domain.

**Comment by PavelBlend** [comment]
Have you used which commit? This scene will work on this commit:
d1848fdecd1318e16e31dcf6ba70921bec1f574f

I will now create a new scene for the last commit.
And it seems to me that the solver has a limit on the number of particles. And because of this, at high resolution many particles are missing.

**Comment by yuanming-hu** [comment]
Thanks for the reply. I confirmed that I'm on  d1848fd and the files are correctly installed.

Error messages:
```
blender ~/test_05\ \(1\)/test_05.blend 

Read prefs: /home/yuanming/.config/blender/2.81/config/userpref.blend
found bundled python: /home/yuanming/blender-2.81a-linux-glibc217-x86_64/2.81/python
[Taichi] mode=release
[Taichi] version 0.5.10, cpu only, commit 58761902, python 3.7.4
Taichi version mismatch. required >= 0.5.11
Installed = 0.5.10
Traceback (most recent call last):
  File "/home/yuanming/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/yuanming/.config/blender/2.81/scripts/addons/taichi_elements/__init__.py", line 27, in <module>
    from . import addon
  File "/home/yuanming/.config/blender/2.81/scripts/addons/taichi_elements/addon.py", line 3, in <module>
    from . import tree, categories, nodes, sockets, operators, handlers
  File "/home/yuanming/.config/blender/2.81/scripts/addons/taichi_elements/operators.py", line 13, in <module>
    from .engine import mpm_solver
  File "/home/yuanming/.config/blender/2.81/scripts/addons/taichi_elements/engine/__init__.py", line 1, in <module>
    from . import mpm_solver
  File "/home/yuanming/.config/blender/2.81/scripts/addons/taichi_elements/engine/mpm_solver.py", line 8, in <module>
    ti.require_version(0, 5, 11)
  File "/home/yuanming/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/site-packages/taichi/core/util.py", line 439, in require_version
    raise Exception("Taichi version mismatch")
Exception: Taichi version mismatch
Read blend: /home/yuanming/test_05 (1)/test_05.blend
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1476 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1476 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1476 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1476 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1476 pyrna_enum_to_py: current value '-1' matches no enum in 'SpaceNodeEditor', '(null)', 'tree_type'

```

**Comment by yuanming-hu** [comment]
Sorry about my poor Python skills, but it seems to me that Suzanna is a box in this scene?

![Screenshot from 2020-04-22 15-12-23](https://user-images.githubusercontent.com/6553256/80023564-b8079480-84ab-11ea-9c9f-76f9224e0245.png)

**Comment by PavelBlend** [comment]
No, this is the bounds display mode. In fact, Suzanne has many polygons. You can change the display type of this object in the Properties window of the Object tab.
![01](https://user-images.githubusercontent.com/7983249/80024066-2d448b00-84e7-11ea-8fd0-1362b8ce353a.jpg)

**Comment by yuanming-hu** [comment]
I see. Now on my end, it seems that no particles are seeded at all :-( I'm not sure what is happening. In order to fix this, could you please do me a favor and share with me a npy file with the triangles? For me debugging is way easier if I can reproduce it outside Blender.

**Comment by PavelBlend** [comment]
Here is Suzanne. It ranges from 0, 0, 0 to 1, 1, 1.
[suzanne.zip](https://github.com/taichi-dev/taichi_elements/files/4518746/suzanne.zip)

**Comment by yuanming-hu** [comment]
Thanks for the Suzanne mesh - I tried to reproduce it outside Blender yet it seems that now the particles are seeded in a reasonable manner. I'm not sure if that is because Blender and the following Python script has different simulator settings:
```python
import taichi as ti
import numpy as np
import utils
from engine.mpm_solver import MPMSolver

write_to_disk = False

# Try to run on GPU
ti.init(arch=ti.cuda)

gui = ti.GUI("Taichi MLS-MPM-99", res=512, background_color=0x112F41)

mpm = MPMSolver(res=(64, 64, 64), size=1)

triangles = np.fromfile('suzanne.npy', dtype=np.float32)
triangles = np.reshape(triangles, (len(triangles) // 9, 9))

mpm.add_mesh(triangles=triangles, material=MPMSolver.material_elastic, color=0xFFFF00)

mpm.set_gravity((0, -20, 0))

for frame in range(1500):
    mpm.step(4e-3)
    particles = mpm.particle_info()
    np_x = particles['position'] / 1.0

    # simple camera transform
    screen_x = ((np_x[:, 0] + np_x[:, 2]) / 2**0.5) - 0.2
    screen_y = (np_x[:, 1])

    screen_pos = np.stack([screen_x, screen_y], axis=-1)

    gui.circles(screen_pos, radius=1.1, color=particles['color'])
    gui.show(f'{frame:06d}.png' if write_to_disk else None)
```

**Comment by PavelBlend** [comment]
Hello, @yuanming-hu 
I think I found the reason for the lack of particles. This error is reproduced at high resolution (256). There are particles, but they have the position 0, 0, 0.
The number of particles that have a non-zero position is 2 ^ 20. I think we need to increase the max_num_particles parameter here:
https://github.com/taichi-dev/taichi_elements/blob/b9140fb57875a0b40b43442c81d35c983f572551/engine/mpm_solver.py#L39
Or even remove the restriction on the maximum number of particles. Since some users have 64 GB of RAM and they will be surprised if a huge number of particles will have a position of 0, 0, 0.
