### ISSUE TITLE
Dependency Installation

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#48]
Make a button in blender that installs all add-on dependencies. This issue is a continuation of this #38 
The button is better placed in the addon settings. With this button you need to install pip then taichi with all the dependencies.

**Comment by PavelBlend** [comment]
I think there is one problem:
How to install a specific version of taichi? Which is not the latest release.
At the moment, the latest version is 0.5.12. But is it possible to install for example 0.5.10?

You need the ability to install any version of taichi, since older versions of the add-on can use older versions of taichi.

**Comment by yuanming-hu** [comment]
If we use PyPI, then we can specify the version of Taichi via `pip3 install taichi==0.5.15`. Maybe a better solution is to let the blender addon depend on `taichi_elements`, then we can simply specify the Taichi version in the `taichi_elements` packages: https://github.com/taichi-dev/taichi_elements/pull/51/files#diff-2eeaed663bd0d25b7e608891384b7298R29
