### ISSUE TITLE
Solver performance

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#50]
I have a question about performance. I ran a simulation with a resolution of 32x32x32. The number of particles is 8500. Here is the calculation time of each frame. More precisely, this is the time spent working on the step function:
https://github.com/taichi-dev/taichi_elements/blob/50ef3232f080030213bcb7578a48d03647a9445b/engine/mpm_solver.py#L273
```
Frame 0: 24.1099 sec
Frame 1: 0.5869 sec
Frame 2: 0.6082 sec
Frame 3: 0.6951 sec
Frame 4: 0.6826 sec
Frame 5: 0.6250 sec
Frame 6: 0.6220 sec
Frame 7: 0.6619 sec
Frame 8: 0.6233 sec
Frame 9: 0.6289 sec
Frame 10: 0.6176 sec
Frame 11: 0.5848 sec
Frame 12: 0.5567 sec
Frame 13: 0.5662 sec
Frame 14: 0.5512 sec
Frame 15: 0.7068 sec
Frame 16: 0.5472 sec
Frame 17: 0.5643 sec
Frame 18: 0.5403 sec
Frame 19: 0.5549 sec
Frame 20: 0.5200 sec
Frame 21: 0.5373 sec
Frame 22: 0.5447 sec
Frame 23: 0.5788 sec
Frame 24: 0.5366 sec
Frame 25: 0.5602 sec
Frame 26: 0.5550 sec
Frame 27: 0.5633 sec
Frame 28: 0.5450 sec
Frame 29: 0.5554 sec
Frame 30: 0.5639 sec
```

why does the first call to step take so much time?

**Comment by yuanming-hu** [comment]
Taichi is a JIT compiler, so at the first time step, it has to compile all the kernels.

**Comment by PavelBlend** [comment]
It turns out that nothing can be done with these?

**Comment by yuanming-hu** [comment]
I'm working on a systematic solution for improving compiling speed, but that will take some time. Actually, if we scale up to high resolution (e.g. 128^3), the compilation time will be negotiable, since simulation time is much longer.
