### ISSUE TITLE
Why is my simulation meeting a bound?

### ISSUE THREAD

**Issue by EaryChow** [taichi-dev/taichi_elements#56]
This is a question. How do I make an unbounded simulation? I thought it would just work but it turned out to still have a bound.
![bounded Sim](https://user-images.githubusercontent.com/59176246/87175314-77e3d100-c2a6-11ea-8239-4f10133b0269.jpg)

**Comment by PavelBlend** [comment]
Install addon from this commit:
https://github.com/taichi-dev/taichi_elements/tree/4079860b5fe7e8e6398ce6605f4e98963a039fc3

Open this scene and bake it:
[unbounded_example.zip](https://github.com/taichi-dev/taichi_elements/files/4904908/unbounded_example.zip)

**Comment by EaryChow** [comment]
@PavelBlend Thanks, that worked. But another question rises. The simulation is now unbounded, but why is the particle seeding still bounded? It looks like only the part within the area in the screenshot below gets seeded, but when the simulation continues, it is indeed an unbounded simulation (second image). 
![Seeding Bound](https://user-images.githubusercontent.com/59176246/87216590-202d8000-c30f-11ea-8177-04482a480abc.jpg)

![Unbounded sim](https://user-images.githubusercontent.com/59176246/87216593-23c10700-c30f-11ea-989e-eeb9ca34faf3.jpg)

**Comment by PavelBlend** [comment]
Unbounded simulator has not yet been completed. The addon is under development. Here's what else to do:
https://github.com/taichi-dev/taichi_elements/issues/15#issuecomment-620178772

**Comment by EaryChow** [comment]
Got it, so I guess it is because negative coordinates are not supported yet, that's why it only seeds on the positive parts.
