### ISSUE TITLE
Emitters not working correctly

### ISSUE THREAD

**Issue by PavelBlend** [taichi-dev/taichi_elements#62]
This error is reproducible in blender 2.90.1.
The error is reproduced on this commit: 3b4182ba734197e4d3db80552750d1c369524150
If there are several emitters and several inflows in the scene, then they will all behave like inflow.
Here is a scene to reproduce the error:
[test_290.zip](https://github.com/taichi-dev/taichi_elements/files/5417811/test_290.zip)

**Comment by yuanming-hu** [comment]
Thanks for reporting this! I'll try to take a look tomorrow.

**Comment by yuanming-hu** [comment]
It seems that Taichi no longer works after I upgrade my Blender to 2.90.1: https://github.com/taichi-dev/taichi/issues/1990

I probably need to fix that first :-( Sorry about the delay...

**Comment by PavelBlend** [comment]
This bug is not reproducible in blender 2.93.0 and taichi_elements in the d3c2c8fa149129fdc8348a89c9735d2e83602151 commit.
I will close this issue.
