### ISSUE TITLE
Non-blocking simulation

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi_elements#7]

**Comment by PavelBlend** [comment]
I made a modal operator (which runs the simulation). But if you run this modal operator, the blender will slow down. There will be friezes. But I created the same operator separately from this addon, and it does not slow down:

```python
import time, threading

import bpy


class TEST_OT_Modal(bpy.types.Operator):
    bl_idname = 'test.modal_test'
    bl_label = 'Test Modal'

    def __init__(self):
        self.is_runnig = False
        self.thread = None
        self.start_time = time.time()

    def thread_code(self):
        while True:
            print(int(time.time() - self.start_time))
            time.sleep(3)

    def run(self):
        self.thread = threading.Thread(
                target=self.thread_code, 
                args=()
        )
        self.thread.start()
        self.is_runnig = True

    def modal(self, context, event):
        if not self.is_runnig:
            self.run()
        return {'PASS_THROUGH'}

    def execute(self, context):
        context.window_manager.modal_handler_add(self)
        self.timer = context.window_manager.event_timer_add(
            0.1, window=context.window
        )
        return {'RUNNING_MODAL'}


bpy.utils.register_class(TEST_OT_Modal)
```

What are the friezes associated with? Do you have any idea why this might be. I can not get the simulator to not slow down the operation of the blender. Or do I need to modify taichi code to speed it up?

**Comment by yuanming-hu** [comment]
Thanks! I'll try to look into this tonight. The holidays end in the US, and I have to go back to work during the day time. I might not be as responsive as previously, but I'll try to do a small feature every day.

**Comment by PavelBlend** [comment]
There is an addon for a blender that is designed to simulate fluid:
https://github.com/rlguy/Blender-FLIP-Fluids
I use this addon, and did not notice any freezes during the simulation. And while the blender interface is not blocked.
The statement that starts the simulation is here:
https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/src/addon/operators/bake_operators.py#L61

You can try to study this operator. Perhaps the reason is that I am not correctly creating the stream for the simulator:
https://github.com/taichi-dev/elements/blob/3d5a6d7b0c3d2622a45fad69b759a966631f6f9c/operators.py#L55

**Comment by yuanming-hu** [comment]
Hi @PavelBlend 

Really sorry about the delay on my end. I have been traveling over the past week and had very limited time to code. I fixed this issue by releasing the Python GIL during Taichi kernel calls. Starting Taichi version v0.3.23 the simulation process is non-blocking.

The initialization process still freezes the GUI since it's not offloaded to Taichi. I'll fix that in https://github.com/taichi-dev/taichi_elements/issues/2

**Comment by yuanming-hu** [comment]
The initialization process is now offloaded to Taichi, so almost no freezing will happen now :-)
