### ISSUE TITLE
no (Force Fields) nodes

### ISSUE THREAD

**Issue by AnasFX** [taichi-dev/taichi_elements#77]
blender : 2.82
taichi_elements : latest
Also : https://github.com/victoriacity/taichi_elements commet

When trying to test the examples in blender there is no (Force Fields) nodes, it shows as red box with (Undefined) title.
Also, Add > Force Fields > Gravity doesn't exist at all.

![image](https://user-images.githubusercontent.com/77914725/132218306-3619b770-3e3f-406c-b90e-547022297de3.png)

**Comment by AnasFX** [comment]
Hi, is there any new news about fixing this issue.
Best regards

**Comment by PavelBlend** [comment]
@AnasFX Where did you download the sample scenes from?
From here?:
https://github.com/taichi-dev/taichi_elements_blender_examples
If so, these scenes are outdated. For them to work properly, you need to download an older version of the blender add-on.
The `Works on commit` column indicates on which commit these scenes were created.

**Comment by AnasFX** [comment]
@PavelBlend That's correct I download it from that link.

Does that mean that we can't use forces in the new versions ? or is there another way of testing taichi_elements in blender ?
If there is a new workflow or help so I can test taichi_elements on blender would you kindly point me to it. Thanks

**Comment by AnasFX** [comment]
@PavelBlend also is there a discord channel for taichi and taichi_elements ? it would be nice to communicate on discord about features and fixing problems.

**Comment by PavelBlend** [comment]
@AnasFX  I will now prepare a blend scene and give you a download link.

**Comment by PavelBlend** [comment]
@AnasFX created scenes:
[taichi_elements_blender_examples.zip](https://github.com/taichi-dev/taichi_elements/files/7228240/taichi_elements_blender_examples.zip)

**Comment by AnasFX** [comment]
@PavelBlend Thank you very much , I will test it and report back

**Comment by AnasFX** [comment]
@PavelBlend Sorry I forgot to mention that I have two gpus, gpu0 : 3090 FE on slot 0, gpu1 : 980ti on slot 1 on the motherboard, and I chose only the 3090 in the CUDA blender preferences 
@PavelBlend the first simple scene doesn't work, the console shows this error :
Read prefs: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend
[Taichi] version 0.8.0, llvm 10.0.0, commit 181c9039, win, python 3.9.2
drop file C:\New folder\taichi_elements_simple_example.blend
Read blend: C:\New folder\taichi_elements_simple_example.blend
[Taichi] Starting on arch=cuda
Creating simulation of res 32, size 4.0
DeprecationWarning: ti.indices is deprecated. Please use ti.axes instead.

  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 247, in init_sim
    solv = mpm_solver.MPMSolver((res, res, res), size=size, unbounded=True)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\engine\mpm_solver.py", line 185, in __init__
    block.dynamic(ti.indices(self.dim),

Voxelizer resolution [32, 32, 32]
Frame: 0
Taichi JIT:0: allocate_from_buffer: block: [6,0,0], thread: [3,0,0] Assertion `Out of CUDA pre-allocated memory.
Consider using ti.init(device_memory_fraction=0.9) or ti.init(device_memory_GB=4) to allocate more GPU memory` failed.
[E 09/24/21 22:38:43.163 3836] [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@86] CUDA Error CUDA_ERROR_ASSERT: device-side assert triggered while calling stream_synchronize (cuStreamSynchronize)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
0x7ff86f4e89ba: taichi::print_traceback in taichi_core.pyd
0x7ff86f3bbc19: PyInit_taichi_core in taichi_core.pyd
0x7ff86f44eb53: PyInit_taichi_core in taichi_core.pyd
0x7ff86f613d1f: taichi::print_traceback in taichi_core.pyd
0x7ff86f46f402: PyInit_taichi_core in taichi_core.pyd
0x7ff86f311bae: PyInit_taichi_core in taichi_core.pyd
0x7ff86f2a6756: PyInit_taichi_core in taichi_core.pyd
0x7ff86f2782bd: pybind11::error_already_set::discard_as_unraisable in taichi_core.pyd
0x7ff8785c6166: PyCFunction_GetFlags in python39.dll
0x7ff87857f677: PyObject_MakeTpCall in python39.dll
0x7ff878581fc1: PyMethod_Self in python39.dll
0x7ff8785f2699: PyType_Ready in python39.dll
0x7ff87857f677: PyObject_MakeTpCall in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878681b45: PyEval_EvalFrameDefault in python39.dll
0x7ff878685baa: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fc24: PyFunction_Vectorcall in python39.dll
0x7ff87868740e: PyEval_GetFuncDesc in python39.dll
0x7ff878683810: PyEval_EvalFrameDefault in python39.dll
0x7ff878685baa: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fc24: PyFunction_Vectorcall in python39.dll
0x7ff87857f4d4: PyObject_FastCallDictTstate in python39.dll
0x7ff87857fec2: PyObject_Call_Prepend in python39.dll
0x7ff8785f268c: PyType_Ready in python39.dll
0x7ff87857f8ff: PyObject_Call in python39.dll
0x7ff87868740e: PyEval_GetFuncDesc in python39.dll
0x7ff878683810: PyEval_EvalFrameDefault in python39.dll
0x7ff878685baa: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fc24: PyFunction_Vectorcall in python39.dll
0x7ff87857f4d4: PyObject_FastCallDictTstate in python39.dll
0x7ff87857fec2: PyObject_Call_Prepend in python39.dll
0x7ff8785f268c: PyType_Ready in python39.dll
0x7ff87857f677: PyObject_MakeTpCall in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878683d48: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff878581ea2: PyMethod_Self in python39.dll
0x7ff87867f149: PyOS_URandomNonblock in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878683d48: PyEval_EvalFrameDefault in python39.dll
0x7ff878685baa: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fc24: PyFunction_Vectorcall in python39.dll
0x7ff878581ea2: PyMethod_Self in python39.dll
0x7ff87867f149: PyOS_URandomNonblock in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878683d9f: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff87867f149: PyOS_URandomNonblock in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878681b45: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff878581ea2: PyMethod_Self in python39.dll
0x7ff87867f149: PyOS_URandomNonblock in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878683d48: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff878581ea2: PyMethod_Self in python39.dll
0x7ff87867f149: PyOS_URandomNonblock in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878683d48: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff878581f26: PyMethod_Self in python39.dll
0x7ff87868740e: PyEval_GetFuncDesc in python39.dll
0x7ff878683810: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff87867f149: PyOS_URandomNonblock in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878683d5e: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff87867f149: PyOS_URandomNonblock in python39.dll
0x7ff87868722f: PyEval_GetFuncDesc in python39.dll
0x7ff878683d5e: PyEval_EvalFrameDefault in python39.dll
0x7ff87857fa21: PyCFunction_Call in python39.dll
0x7ff87857fb1e: PyFunction_Vectorcall in python39.dll
0x7ff878581f26: PyMethod_Self in python39.dll
0x7ff87851c526: PyOS_SigintEvent in python39.dll
0x7ff8787055b2: PyThread_init_thread in python39.dll
0x7ff965376c0c: recalloc in ucrtbase.dll
0x7ff9668d54e0: BaseThreadInitThunk in KERNEL32.DLL
0x7ff9677a485b: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/docs/lang/articles/misc/install
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 261, in init_sim
    self.run_sim()
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 182, in run_sim
    self.create_emitters(frame)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 130, in create_emitters
    create_emitter(self.solv, emitter, vel)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 108, in create_emitter
    solv.add_mesh(triangles=tris, material=ti_mat, color=color, velocity=vel)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\engine\mpm_solver.py", line 986, in add_mesh
    self.voxelizer.voxelize(triangles)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\engine\voxelizer.py", line 126, in voxelize
    self.voxelize_triangles(num_triangles, triangles)
  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\site-packages\taichi\lang\kernel_impl.py", line 738, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\site-packages\taichi\lang\kernel_impl.py", line 606, in __call__
    return self.compiled_functions[key](*args)
  File "C:\blender-2.93.4-windows-x64\2.93\python\lib\site-packages\taichi\lang\kernel_impl.py", line 563, in func__
    t_kernel(launch_ctx)
RuntimeError: [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@86] CUDA Error CUDA_ERROR_ASSERT: device-side assert triggered while calling stream_synchronize (cuStreamSynchronize)

**Comment by AnasFX** [comment]
@PavelBlend I will try the  LTS Release 2.93.0 Version as you mentioned and report back

**Comment by AnasFX** [comment]
@PavelBlend unfortunately even with version 2.93.0 I have this error. I tried to check the 980ti alone in the preferences, even checked my cpu only, with no luck. It falls back to cuda, but displays this error

[Taichi] Starting on arch=cuda
Creating simulation of res 32, size 4.0
DeprecationWarning: ti.indices is deprecated. Please use ti.axes instead.

  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 247, in init_sim
    solv = mpm_solver.MPMSolver((res, res, res), size=size, unbounded=True)
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\engine\mpm_solver.py", line 185, in __init__
    block.dynamic(ti.indices(self.dim),

Voxelizer resolution [32, 32, 32]
Frame: 0
Taichi JIT:0: allocate_from_buffer: block: [6,0,0], thread: [3,0,0] Assertion `Out of CUDA pre-allocated memory.
Consider using ti.init(device_memory_fraction=0.9) or ti.init(device_memory_GB=4) to allocate more GPU memory` failed.
[E 09/24/21 23:09:33.947 15612] [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@86] CUDA Error CUDA_ERROR_ASSERT: device-side assert triggered while calling stream_synchronize (cuStreamSynchronize)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
0x7ff86ee589ba: taichi::print_traceback in taichi_core.pyd
0x7ff86ed2bc19: PyInit_taichi_core in taichi_core.pyd
0x7ff86edbeb53: PyInit_taichi_core in taichi_core.pyd
0x7ff86ef83d1f: taichi::print_traceback in taichi_core.pyd
0x7ff86eddf402: PyInit_taichi_core in taichi_core.pyd
0x7ff86ec81bae: PyInit_taichi_core in taichi_core.pyd
0x7ff86ec16756: PyInit_taichi_core in taichi_core.pyd
0x7ff86ebe82bd: pybind11::error_already_set::discard_as_unraisable in taichi_core.pyd
0x7ff878b36166: PyCFunction_GetFlags in python39.dll
0x7ff878aef677: PyObject_MakeTpCall in python39.dll
0x7ff878af1fc1: PyMethod_Self in python39.dll
0x7ff878b62699: PyType_Ready in python39.dll
0x7ff878aef677: PyObject_MakeTpCall in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf1b45: PyEval_EvalFrameDefault in python39.dll
0x7ff878bf5baa: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefc24: PyFunction_Vectorcall in python39.dll
0x7ff878bf740e: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3810: PyEval_EvalFrameDefault in python39.dll
0x7ff878bf5baa: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefc24: PyFunction_Vectorcall in python39.dll
0x7ff878aef4d4: PyObject_FastCallDictTstate in python39.dll
0x7ff878aefec2: PyObject_Call_Prepend in python39.dll
0x7ff878b6268c: PyType_Ready in python39.dll
0x7ff878aef8ff: PyObject_Call in python39.dll
0x7ff878bf740e: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3810: PyEval_EvalFrameDefault in python39.dll
0x7ff878bf5baa: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefc24: PyFunction_Vectorcall in python39.dll
0x7ff878aef4d4: PyObject_FastCallDictTstate in python39.dll
0x7ff878aefec2: PyObject_Call_Prepend in python39.dll
0x7ff878b6268c: PyType_Ready in python39.dll
0x7ff878aef677: PyObject_MakeTpCall in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3d48: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878af1ea2: PyMethod_Self in python39.dll
0x7ff878bef149: PyOS_URandomNonblock in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3d48: PyEval_EvalFrameDefault in python39.dll
0x7ff878bf5baa: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefc24: PyFunction_Vectorcall in python39.dll
0x7ff878af1ea2: PyMethod_Self in python39.dll
0x7ff878bef149: PyOS_URandomNonblock in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3d9f: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878bef149: PyOS_URandomNonblock in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf1b45: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878af1ea2: PyMethod_Self in python39.dll
0x7ff878bef149: PyOS_URandomNonblock in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3d48: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878af1ea2: PyMethod_Self in python39.dll
0x7ff878bef149: PyOS_URandomNonblock in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3d48: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878af1f26: PyMethod_Self in python39.dll
0x7ff878bf740e: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3810: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878bef149: PyOS_URandomNonblock in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3d5e: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878bef149: PyOS_URandomNonblock in python39.dll
0x7ff878bf722f: PyEval_GetFuncDesc in python39.dll
0x7ff878bf3d5e: PyEval_EvalFrameDefault in python39.dll
0x7ff878aefa21: PyCFunction_Call in python39.dll
0x7ff878aefb1e: PyFunction_Vectorcall in python39.dll
0x7ff878af1f26: PyMethod_Self in python39.dll
0x7ff878a8c526: PyOS_SigintEvent in python39.dll
0x7ff878c755b2: PyThread_init_thread in python39.dll
0x7ff965376c0c: recalloc in ucrtbase.dll
0x7ff9668d54e0: BaseThreadInitThunk in KERNEL32.DLL
0x7ff9677a485b: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/docs/lang/articles/misc/install
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 261, in init_sim
    self.run_sim()
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 182, in run_sim
    self.create_emitters(frame)
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 130, in create_emitters
    create_emitter(self.solv, emitter, vel)
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 108, in create_emitter
    solv.add_mesh(triangles=tris, material=ti_mat, color=color, velocity=vel)
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\engine\mpm_solver.py", line 986, in add_mesh
    self.voxelizer.voxelize(triangles)
  File "C:\blender-2.93.0-windows-x64\2.93\scripts\addons\taichi_elements\engine\voxelizer.py", line 126, in voxelize
    self.voxelize_triangles(num_triangles, triangles)
  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\site-packages\taichi\lang\kernel_impl.py", line 738, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\site-packages\taichi\lang\kernel_impl.py", line 606, in __call__
    return self.compiled_functions[key](*args)
  File "C:\blender-2.93.0-windows-x64\2.93\python\lib\site-packages\taichi\lang\kernel_impl.py", line 563, in func__
    t_kernel(launch_ctx)
RuntimeError: [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@86] CUDA Error CUDA_ERROR_ASSERT: device-side assert triggered while calling stream_synchronize (cuStreamSynchronize)

**Comment by AnasFX** [comment]
I do remember something like this message, the problem was about choosing how much VRam for the device_memory :

Taichi JIT:0: allocate_from_buffer: block: [6,0,0], thread: [3,0,0] Assertion Out of CUDA pre-allocated memory. Consider using ti.init(device_memory_fraction=0.9) or ti.init(device_memory_GB=4) to allocate more GPU memory failed

but I don't remember the fix, any thoughts ?

**Comment by PavelBlend** [comment]
I have tested the simulator on taichi 0.7.32. Taichi 0.8.0 was released two days ago.
Try to install taichi version 0.7.32:
`pip install taichi==0.7.32`
If the problem persists, then turn off the rendering with cuda.
To do this, you need to change the line here:
https://github.com/taichi-dev/taichi_elements/blob/e6d2db2b74f5177a1bdd615d485f49ca0fcfb9d3/blender/operators.py#L245

change to:
`ti.init(arch=ti.cpu)`
or
`ti.init(arch=ti.cuda, device_memory_GB=4)`

**Comment by PavelBlend** [comment]
@AnasFX I updated the addon. Download the latest commit:
https://github.com/taichi-dev/taichi_elements/tree/d33bf33042b75cc8452b6b8f5ecdb2aeb093884e
I added parameters for the Simulate button:
![01](https://user-images.githubusercontent.com/7983249/134746010-628b17b7-2232-4af4-b8ee-f48249574f95.jpg)

**Comment by AnasFX** [comment]
@PavelBlend That actually did the trick. The simple scene works on the latest Taichi 0.8.0.
Water - Snow - Elastic - Sand - Stationary all work on CPU and GPU.

When I press Simulate I can see where the cache files are, but when I press Render I can't see where are the rendered images , is this normal, are they saved automatically or should I assign a save node ?

**Comment by PavelBlend** [comment]
@AnasFX the render is saved here:
![01](https://user-images.githubusercontent.com/7983249/134748468-e0e87f7e-c253-4628-8709-a76d815bdde2.jpg)

**Comment by AnasFX** [comment]
@PavelBlend Thank you very much, Can you help me to know what is the function of the Render button ?
![0020](https://user-images.githubusercontent.com/77914725/134749646-796d4bfd-ea69-4696-8065-b4b40dc91b46.png)

I assumed that the Render button would mesh the particles with some kind of a meshing algorithm to get a solid representation of the particles so it can be rendered directly without the need to create a heavy dense mesh. Is my assumption correct ? or should we use another method to convert and render these particles to a mesh, something like rendering Jelly or Water

I also noticed that after it uses the memory and finishes the simulation it doesn't release the memory, and when you render with the GPU nothing would be left for the rendering process, is this normal, or can is there some king of way to at least make it release the memory manually , some thing like a button similar to the one that you created ?

**Comment by PavelBlend** [comment]
@AnasFX if you start rendering with the standard button, the blender will often crash. So I added a render button that renders the animation frame by frame, rendering it single frames, but in automatic mode. This makes the rendering of the particles more stable.

The button has no other functions.

For the particles to be visible on the render, you need to set up the default particle system. Or use dupli-verts for the mesh object.

As for the memory, I don't know exactly why it is not released. I will deal with this later.

**Comment by AnasFX** [comment]
@PavelBlend Thank you so much for the detailed explanation, for the quick reply and for the quick fix. I will continue testing, and if I had any issues I will report them here.
Best regards

**Comment by AnasFX** [comment]
@PavelBlend Hi, I have a question please, is there a way to implement a collider node so one can use objects for collisions ?
I found only a Ground node, but nothing else that can be used as a collision object.

**Comment by PavelBlend** [comment]
@AnasFX Hi. There are no colliders at this time. The only colliders are ground.
But recently, static particles have been added that can replace colliders. Add an emitter with Stationary material. And it will be necessary to remove static particles from the render in some way. Probably this can be done using the Transparent BSDF node. And static particles should be, for example, black (0, 0, 0) so that they can be easily filtered using the nodes in the Shader Editor.

**Comment by AnasFX** [comment]
@PavelBlend Sorry I couldn't figure out how to use the stationary particles with the normal particles as a collider, could you give me an example how to use them both.

**Comment by AnasFX** [comment]
@PavelBlend I manged to figure out how to use the stationary particle, unfortunately the results are not good and can not be used like a ground or a normal collider, also I believe the increase in particles would lead to unnecessary overhead simulation power and time 😞
