### ISSUE TITLE
taichi-dev / taichi_elements无法运行demo示例

### ISSUE THREAD

**Issue by jack0596cn** [taichi-dev/taichi_elements#78]
[Taichi] mode=release
[Taichi] version 0.7.10, llvm 10.0.0, commit 0f0205fc, win, python 3.6.8
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "E:/taichi_elements/demo/demo_3d_letters.py", line 54, in <module>
    mpm = MPMSolver(res=(R, R, R), size=1, unbounded=True, dt_scale=1)
  File "E:\taichi_elements\engine\mpm_solver.py", line 180, in __init__
    block_component(grid_v.get_scalar_field(i))
AttributeError: 'Matrix' object has no attribute 'get_scalar_field'

Process finished with exit code 1

**Comment by jack0596cn** [comment]
同时试了taichi 0.7.31版本，问题依旧

**Comment by jack0596cn** [comment]
> > 同时试了taichi 0.7.31版本，问题依旧
> 
> Thanks for reporting. I tried the examples with Taichi `0.7.31` and they work well. Could you retry?

taichi 0.7.31 的例子没问题，可以运行的。elements的demo无法运行，我想尝试下elements的例子，就出现了上面的问题，后来我就尝试将taichi安装版本切换为0.7.31，elements的例子依然无法运行。

**Comment by yuanming-hu** [comment]
Interesting... Could you share with me the full error log with Taichi 0.7.31? It seems that `get_scalar_field` is already supported in that version.

**Comment by jack0596cn** [comment]
> > Interesting... Could you share with me the full error log with Taichi 0.7.31? It seems that `get_scalar_field` is already supported in that version.
> 
> C:\Programs\Python\Python36\python.exe E:/taichi_elements/demo/demo_3d_letters.py
> [Taichi] version 0.7.30, llvm 10.0.0, commit cee45665, win, python 3.6.8
> [Taichi] Starting on arch=cuda
> Voxelizer resolution [256, 256, 256]
> loading taichi.ply
> loaded
> frame 0
> needed substeps: 26
> .Traceback (most recent call last):
> File "E:/taichi_elements/demo/demo_3d_letters.py", line 100, in
> mpm.step(2e-3, print_stat=True)
> File "E:\taichi_elements\engine\mpm_solver.py", line 724, in step
> self.build_pid(self.pid, self.grid_m, 0.5)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 725, in **call**
> return self._primal(self._kernel_owner, *args, **kwargs)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 592, in **call**
> key = self.ensure_compiled(*args)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 583, in ensure_compiled
> self.materialize(key=key, args=args, arg_features=arg_features)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 452, in materialize
> taichi_kernel = taichi_kernel.define(taichi_ast_generator)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 447, in taichi_ast_generator
> compiled()
> File "E:\taichi_elements\engine\mpm_solver.py", line 322, in build_pid
> base_pid = ti.rescale_index(grid_m, pid.parent(2), base)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\ops.py", line 934, in rescale_index
> assert isinstance(b, Field), f"second argument must be a field"
> AssertionError: second argument must be a field
> 
> Process finished with exit code 1

注：能够安装的最高版本是0.7.30，install没有31版本

**Comment by jack0596cn** [comment]
> > Interesting... Could you share with me the full error log with Taichi 0.7.31? It seems that `get_scalar_field` is already supported in that version.
> 
> C:\Programs\Python\Python36\python.exe E:/taichi_elements/demo/demo_3d_letters.py
> [Taichi] version 0.7.30, llvm 10.0.0, commit cee45665, win, python 3.6.8
> [Taichi] Starting on arch=cuda
> Voxelizer resolution [256, 256, 256]
> loading taichi.ply
> loaded
> frame 0
> needed substeps: 26
> .Traceback (most recent call last):
> File "E:/taichi_elements/demo/demo_3d_letters.py", line 100, in
> mpm.step(2e-3, print_stat=True)
> File "E:\taichi_elements\engine\mpm_solver.py", line 724, in step
> self.build_pid(self.pid, self.grid_m, 0.5)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 725, in **call**
> return self._primal(self._kernel_owner, *args, **kwargs)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 592, in **call**
> key = self.ensure_compiled(*args)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 583, in ensure_compiled
> self.materialize(key=key, args=args, arg_features=arg_features)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 452, in materialize
> taichi_kernel = taichi_kernel.define(taichi_ast_generator)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\kernel_impl.py", line 447, in taichi_ast_generator
> compiled()
> File "E:\taichi_elements\engine\mpm_solver.py", line 322, in build_pid
> base_pid = ti.rescale_index(grid_m, pid.parent(2), base)
> File "C:\Programs\Python\Python36\lib\site-packages\taichi\lang\ops.py", line 934, in rescale_index
> assert isinstance(b, Field), f"second argument must be a field"
> AssertionError: second argument must be a field
> 
> Process finished with exit code 1

注：能够安装的最高版本是0.7.30，install没有31版本，demo_3d_letters.py运行所需的taichi.ply我也下载放到了对应目录

**Comment by yuanming-hu** [comment]
Interesting... You probably need Taichi 0.7.31. Could you open up a PR in https://github.com/taichi-dev/taichi/issues reporting that the Windows+Python 3.6 version is not released? https://pypi.org/project/taichi/0.7.31/#files

A quick solution is to use Python 3.7 instead.

**Comment by jack0596cn** [comment]
> Interesting... You probably need Taichi 0.7.31. Could you open up a PR in https://github.com/taichi-dev/taichi/issues reporting that the Windows+Python 3.6 version is not released? https://pypi.org/project/taichi/0.7.31/#files
> 
> A quick solution is to use P

> Interesting... You probably need Taichi 0.7.31. Could you open up a PR in https://github.com/taichi-dev/taichi/issues reporting that the Windows+Python 3.6 version is not released? https://pypi.org/project/taichi/0.7.31/#files
> 
> A quick solution is to use Python 3.7 instead.

**Comment by jack0596cn** [comment]
> > Interesting... You probably need Taichi 0.7.31. Could you open up a PR in https://github.com/taichi-dev/taichi/issues reporting that the Windows+Python 3.6 version is not released? https://pypi.org/project/taichi/0.7.31/#files
> > A quick solution is to use P
> 
> > Interesting... You probably need Taichi 0.7.31. Could you open up a PR in https://github.com/taichi-dev/taichi/issues reporting that the Windows+Python 3.6 version is not released? https://pypi.org/project/taichi/0.7.31/#files
> > A quick solution is to use Python 3.7 instead.

好的，我是用3.7试一下
